Fix #24 by correcting logic to determine if diagram needs to be generated or not. The source.newer? check was causing too much code to be skipped that was needed later. This caused a NoSuchMethodError since the metadata variable was set to nil.